spring:
  application:
    name: rasplus-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rasmoo-edtech/rasplus-config-server-repo
          search-paths:
            - customer
            - message
            - data
          default-label: main
server:
  port: 8888
